import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sumiclean",
  description: "Generated by create next app",
};

import { AgendamentoProvider } from "../../src/app/context/contextApi";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <AgendamentoProvider>
          {children}
        </AgendamentoProvider>
      </body>
    </html>
  );
}
